
services:
  - type: web
    name: pp2-m8-clase-3-ejerc-1-jvs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PRODUCTION_HOST
        sync: false
